import "./globals.css";
import { Inter } from "next/font/google";
import Instagram from "public/instagram.ico"
import Navigation from "./components/navigation/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My IG",
  description: "Generated by create next app",
  icons: [{rel: 'icon', url: Instagram.src}]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        {children}
      </body>
    </html>
  );
}
