import "./globals.css";
import { Inter } from "next/font/google";
import Instagram from "public/instagram.ico";
// import Button from '@mui/material/Button';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My IG",
  description: "Generated by create next app",
  icons: [{rel: 'icon', url: Instagram.src}],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
      </body>
    </html>
  );
}
